apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
  annotations:
    "helm.sh/hook": pre-install
data:
  application.port: {{ .Values.application.http.port | quote }}
  application.db.generation: {{ .Values.application.hibernate.generation }}
  application.db.log: {{ .Values.application.hibernate.log }}