apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-crud.fullname" . }}-changelog-config
  annotations:
    "helm.sh/hook": pre-install
data:
  changelog: |
    {{ .Values.migration.changelog | nindent 4 }}
