apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  db_url: {{ include "user-crud.fullUrl" . | b64enc }}
  db_name: {{ .Values.db.connection.name | b64enc }}
  db_username: {{ .Values.db.connection.username | b64enc }}
  db_password: {{ .Values.db.connection.password | b64enc }}