apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-crud.fullname" . }}-svc-app
  labels:
    {{- include "user-crud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.application.http.port }}
      protocol: TCP
  selector:
    {{- include "user-crud.selectorLabels" . | nindent 4 }}
