FROM openjdk:17-jdk-slim

MAINTAINER Vyacheslav Denisenko <denisenko.ve21@gmail.com>

COPY target/quarkus-app/lib/ /deployments/lib/
COPY target/quarkus-app/*.jar /deployments/
COPY target/quarkus-app/app/ /deployments/app/
COPY target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0"

ENTRYPOINT [ "java", "-jar", "/deployments/quarkus-run.jar" ]